version: "3"
services:
  jobmanager:
    image: pyflink:1.14.0
    volumes:
    - ./code:/home/pyflink
    working_dir: /home/pyflink
    ports:
      - "8085:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - flink_network
  
  taskmanager:
    image: pyflink:1.14.0
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - flink_network

networks:
  flink_network:
    name: docker_network
    external: true